[package]
name = "cfgseq"
version = "0.1.0"
authors = ["ibzieg <ian.b.zieg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portmidi = "^0.2"
serde = "^1.0.108"
serde_json = "^1.0.56"
docopt = "^1.1.0"